spring:
  application:
    name: social
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "xxx"
            client-secret: "xxx"

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/social
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver